sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t paulalavagna/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true paulalavagna/docker-react npm run test